### PR TITLE
Create Smoother.java utility class

### PR DESCRIPTION
**Pull request by ptwu**
For use with SmoothDrive

### CODE REVIEW

**Comment by xavierlyu** [comment]
call it something else and fix the formatting

**Comment by ptwu** [comment]
ok I fixed the formatting but I like the Smoother name. Do you have any suggestions for what it should be changed to?

**Comment by TimMagoun** [comment]
If we're using PID, there's no need for smoothing...

**Comment by ptwu** [comment]
Sorry I thought we were still using joysticks. My bad

**Comment by TimMagoun** [comment]
We're using the integrated PID system in the Talons themselves, which is easier than handing the PID by hand or by smoothing. We can still use the joysticks or the controller, although we're leaning towards using the controller right now.

**Pull request closed without merging**
