### PR TITLE
Shooter

### PR DESCRIPTION
**Pull request by abhitekula**

### CODE REVIEW

**Comment by jamesw343** [comment]
Rip you used tabs lol

**Comment by TimMagoun** [comment]
Seriously though? I thought we're all using spaces now...

**Comment by xavierlyu** [comment]
go with spaces 
https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

**Comment by TimMagoun** [comment]
It's integrated in our eclipse preference settings

**Comment by jamesw343** [comment]
Your master branch is out of date too

**Comment by TimMagoun** [comment]
Does anyone want to fix this merge?

**Comment by jamesw343** [comment]
I'll try later tonight

**Comment by jamesw343** [comment]
Fixed merged issues and did some more cleaning up (esp. with vision code). I'll make a new PR once the code is tested (latest is currently on my fork).

**Comment by TimMagoun** [comment]
Implemented in #82

**Pull request closed without merging**
