### PR TITLE
Vision formatted

### PR DESCRIPTION
**Pull request by TimMagoun**

### CODE REVIEW

**Comment by jamesw343** [comment]
Not a good idea, the packages are all different

**Comment by TimMagoun** [comment]
I manually changed them while merging

**Comment by jamesw343** [comment]
The new merged files are still in the old packages though

https://github.com/Team1923/Steamworks_2017/tree/vision_formatted/src/org/usfirst/frc/team1923/robot/commands

**Comment by TimMagoun** [comment]
Okay I'll change it to the new system.

**Comment by TimMagoun** [comment]
Fixed

**Pull request merged**
