### PR TITLE
Driving forward for two seconds to cross baseline if negative ultraso…

### PR DESCRIPTION
**Pull request by Asap7772**
…nic value

Chinmay stated that a problem they faced in competition is that the ultrasonic read a negative reading at times. He wanted me to have the robot cross the baseline (drive forward for 2 seconds at 80% power) if this occured.

### CODE REVIEW

**Review by abhitekula — COMMENTED** [review]
Don't actually merge anything without testing it on the robot. We want the actually GitHub repository to have code that we know 100% works.

**Comment by jamesw343** [comment]
Calling `new DriveTimeCommand(...)` will only instantiate the object, it won't actually schedule it to run.

**Comment by Asap7772** [comment]
Yes, I would have to change this into a CommandGroup and then addSequential() the command. I realized this after I created the pull request. The other problem that I saw was that after this command was run, the vision auton center would drop the gear. This needs to be fixed (possibly by putting the boolean in the drive subsystem and then checking the boolean in the vision center. I will fix the errors and test before creating a pull request.

**Comment by TimMagoun** [comment]
Okay first you can't add a conditional into the command group because it is
ran only once upon instantiation. Second I'm not particularly fond of
adding more random booleans into our vision code, is there another way to
do this?

**Comment by abhitekula** [comment]
In order to fix the shooting gear and in my opinion make the auton better, make it so that is the ultrasonic value is below 4 or whatever because that's the lowest the ultrasonic reads and if it is use the width of the contour for the is finished. This way the gear should still be placed even if the ultrasonic is reporting negative or wrongish values.

**Comment by jamesw343** [comment]
We don't have time to test it though.

**Comment by TimMagoun** [comment]
We might have a little time on practice day

**Comment by jamesw343** [comment]
Not unless you're going early. Practice matches end noon, we leave at 10.

**Comment by TimMagoun** [comment]
Well then I guess we wont implement it

**Pull request closed without merging**
