### PR TITLE
Vision formatted

### PR DESCRIPTION
**Pull request by TimMagoun**
Just merging this to master because it works

### CODE REVIEW

**Comment by TimMagoun** [comment]
Oh and master was on tab instead of spaces, this should fix that

**Review by Asap7772 — APPROVED** [review]
This code is stable and well formatted. It can be pushed to the master branch.

**Review by abhitekula — APPROVED** [review]
Looks good to me.

**Comment by jamesw343** [comment]
Look at PR #79 before merge please, some code here is outdated / untested.

**Pull request merged**
