### PR TITLE
Tune PigeonIMU turning

### PR DESCRIPTION
**Pull request by jamesw343**

### CODE REVIEW

**Comment by TimMagoun** [comment]
This series of commits is kinda messed up... Maybe rebase? I'll look into it

**Comment by TimMagoun** [comment]
I think I can just make the changes locally and push. You should probably reset and pull after the team branch is up to date. This makes the commits on beta a whole lot cleaner.

**Comment by jamesw343** [comment]
It's because I pulled the messed up beta branch and reverted it. Commit 68e84d4 should have undone dd5a294 through c5c5cad. I'll see what I can do to fix it though.

**Comment by TimMagoun** [comment]
I'll just make the changes and push it up. You can do a reset hard to a
earlier commit and then pull from upstream

**Pull request closed without merging**
